### ISSUE TITLE
Error booting on mac with vagrant and virtualbox

### ISSUE THREAD

**Issue by ghost** [ntt-sic/masakari-deploy#15]
Just tried out the vagrant file, changed config.box.vm to be centos and downloaded the centos 7 box... booted up and was met with a wall of errors like this 

> => controller: ================================================================================
==> controller: Recipe Compile Error in /var/chef/cache/cookbooks/devstack/recipes/default.rb
==> controller: ================================================================================
==> controller: 
==> controller: 
==> controller: NoMethodError
==> controller: -------------
==> controller: 
==> controller: undefined method `supports' for Chef::Resource::User::LinuxUser
==> controller: 
==> controller: Cookbook Trace:
==> controller: ---------------
==> controller:   /var/chef/cache/cookbooks/devstack/recipes/default.rb:8:in `block in from_file'
==> controller:   /var/chef/cache/cookbooks/devstack/recipes/default.rb:7:in `from_file'
==> controller: 
==> controller: Relevant File Content:
==> controller: ----------------------
==> controller: /var/chef/cache/cookbooks/devstack/recipes/default.rb:
==> controller: 
==> controller:   1:  %w{git}.each do |pkg|
==> controller:   2:    package pkg do
==> controller:   3:      action :install
==> controller:   4:    end
==> controller:   5:  end
==> controller:   6:  
==> controller:   7:  user "stack" do
==> controller:   8>>   supports :manage_home => true
==> controller:   9:    comment 'devstack user'
==> controller:  10:    home '/home/stack'
==> controller:  11:    shell '/bin/bash'
==> controller: 
==> controller:  12:    action :create
==> controller:  13:  end
==> controller:  14:  
==> controller:  15:  template "/etc/sudoers.d/stack" do
==> controller:  16:    source 'sudoers.d.stack.erb'
==> controller:  17:    mode '0440'
==> controller: 
==> controller: 
==> controller: System Info:
==> controller: ------------
==> controller: chef_version=13.8.5
==> controller: 
==> controller: platform=centos
==> controller: platform_version=7.4.1708
==> controller: 
==> controller: ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
==> controller: program_name=chef-solo worker: ppid=20328;start=13:43:49;
==> controller: executable=/opt/chef/bin/chef-solo
==> controller: 
==> controller: 
==> controller: [2018-03-13T13:43:52+00:00] DEBUG: Filtered backtrace of compile error: /var/chef/cache/cookbooks/devstack/recipes/default.rb:8:in `block in from_file',/var/chef/cache/cookbooks/devstack/recipes/default.rb:7:in `from_file'
==> controller: [2018-03-13T13:43:52+00:00] DEBUG: Filtered backtrace of compile error: /var/chef/cache/cookbooks/devstack/recipes/default.rb:8:in `block in from_file',/var/chef/cache/cookbooks/devstack/recipes/default.rb:7:in `from_file'
==> controller: [2018-03-13T13:43:52+00:00] DEBUG: Backtrace entry for compile error: '/var/chef/cache/cookbooks/devstack/recipes/default.rb:8:in `block in from_file''
==> controller: [2018-03-13T13:43:52+00:00] DEBUG: Backtrace entry for compile error: '/var/chef/cache/cookbooks/devstack/recipes/default.rb:8:in `block in from_file''
==> controller: [2018-03-13T13:43:52+00:00] DEBUG: Line number of compile error: '8'
==> controller: [2018-03-13T13:43:52+00:00] DEBUG: Line number of compile error: '8'

finally resulting in a fatal exit 

>==> controller: /bin/chef-solo:59:in `load'
==> controller: /bin/chef-solo:59:in `<main>'
==> controller: [2018-03-13T13:43:52+00:00] ERROR: undefined method `supports' for Chef::Resource::User::LinuxUser
==> controller: [2018-03-13T13:43:52+00:00] ERROR: undefined method `supports' for Chef::Resource::User::LinuxUser
==> controller: [2018-03-13T13:43:52+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
==> controller: [2018-03-13T13:43:52+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

**Comment by ghost** [comment]
Could it be due to this ?

Chef.log_deprecation "setting supports on the linux_user resource is deprecated" 

found here 

https://github.com/chef/chef/issues/5318
